version: '3.8'

services:
  # RAG应用服务
  rag-app:
    image: shusanbei/rag-app:yjz
    container_name: rag-app
    restart: always
    ports:
      - "19500:19500"
    environment:
      - MILVUS_URI=http://8.216.91.252:19530
      # - PGvector_url=postgresql://pgvector:pgvector@pgvector:5432/pgvector
      - XINFERENCE_HOST=http://8.216.91.252:9997
      - OLLAMA_HOST=http://8.216.91.252:11434
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=19500
      - TZ=Asia/Shanghai
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge